### ISSUE TITLE
Avoid using implementation-reserved identifiers for include guards

### ISSUE THREAD

**Issue by cvtsi2sd** [green7ea/cpp-compilation#6]
I don't know where does this widespread idea of using double-underscore-prefixed names for header guards, but it's non-compliant.

As per [[lex.name] ¶3](http://eel.is/c++draft/lex.name#3) (recent versions of the standard) or [global.names] (older versions):

> In addition, some identifiers are reserved for use by C++ implementations and shall not be used otherwise; no diagnostic is required.
> - Each identifier that contains a double underscore `__` or begins with an underscore followed by an uppercase letter is reserved to the implementation for any use.
> - Each identifier that begins with an underscore is reserved to the implementation for use as a name in the global namespace.

So, by doing `#ifdef __FILENAME__` you are stepping on the implementation's feet. Just do something like `#ifdef FILENAME_INCLUDED` and leave names with double underscores alone.

**Comment by green7ea** [comment]
Thank you for taking the time to link to the standard, much appreciated.
